name: Morajlab assets API action
on: [push]
jobs:
  Create-API-Action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: |
        npm install
    - name: Create API JSON files
      run: |
        npm run scripts
